[package]
name = "try_test_features"
version = "0.1.0"
authors = ["Patrik Stas <patrik.stas@absa.africa>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["AAA"]
#default = []
AAA = []
BBB = []
PPP = []
PPP_extra = []

[dependencies]
